"use client";

import { useState } from "react";
import { players, simulateMatch } from "@/lib/game";

const nav = ["HOME", "SQUAD", "TACTICS", "TRANSFERS", "FIXTURES", "TABLE", "TRAINING", "YOUTH"];
const opponents = ["Northbridge United", "Kingsport City", "Westford Athletic", "Harbor Town"];

export default function Game() {
  const [active, setActive] = useState("HOME");
  const [match, setMatch] = useState<{gf:number;ga:number;events:string[]}|null>(null);
  const [mentality, setMentality] = useState("Balanced");
  const [week, setWeek] = useState(1);
  const [notice, setNotice] = useState("");

  const simulate = () => { setMatch(simulateMatch(84, 80, true, mentality)); setNotice("Match simulated — squad form and league results updated."); };
  const nextWeek = () => { setWeek(w=>w+1); setMatch(null); setNotice("Advanced to the next matchweek."); };

  return <main className="min-h-screen bg-[#070a0e] text-white">
    <header className="sticky top-0 z-30 border-b border-[#27303c] bg-[#090d12]/95 backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-lg bg-[#b7ff39] font-black text-black">FC</div><div><p className="text-[9px] font-black tracking-[.3em] text-[#b7ff39]">CAREER MODE</p><p className="font-black">RIVERSIDE FC</p></div></div><div className="hidden items-center gap-8 md:flex"><div><small className="label">SEASON</small><b>2026/27</b></div><div><small className="label">WEEK</small><b>{week}</b></div><div><small className="label">BUDGET</small><b className="text-[#b7ff39]">€86.4M</b></div><div><small className="label">BOARD</small><b>78%</b></div></div><button onClick={()=>setNotice("Career saved successfully.")} className="rounded-lg border border-[#303944] px-4 py-2 text-xs font-black hover:border-[#b7ff39]">SAVE</button></div></header>
    <div className="mx-auto flex max-w-[1500px]">
      <aside className="hidden w-56 shrink-0 border-r border-[#27303c] p-4 lg:block"><p className="label mb-3 px-3">MANAGEMENT</p>{nav.map(x=><button key={x} onClick={()=>setActive(x)} className={`mb-1 w-full rounded-lg px-3 py-3 text-left text-xs font-black tracking-wider ${active===x?"bg-[#b7ff39] text-black":"text-[#87929e] hover:bg-[#151b22] hover:text-white"}`}>{x}</button>)}<div className="mt-8 rounded-xl border border-[#27303c] bg-[#10151c] p-4"><p className="label">NEXT MATCH</p><p className="mt-2 font-black">vs Northbridge</p><p className="mt-1 text-xs text-[#737e89]">Saturday · 19:45</p></div></aside>
      <section className="min-w-0 flex-1 p-5 md:p-8">
        {notice && <div className="mb-5 rounded-xl border border-[#b7ff39]/30 bg-[#b7ff39]/10 px-4 py-3 text-sm font-bold text-[#b7ff39]">✓ {notice}</div>}
        {active === "HOME" && <Home match={match} mentality={mentality} setMentality={setMentality} simulate={simulate} nextWeek={nextWeek} />}
        {active === "SQUAD" && <Squad />}
        {active === "TACTICS" && <Tactics mentality={mentality} setMentality={setMentality} />}
        {active === "TRANSFERS" && <Transfers />}
        {active === "FIXTURES" && <Fixtures />}
        {active === "TABLE" && <Table />}
        {active === "TRAINING" && <Training />}
        {active === "YOUTH" && <Youth />}
      </section>
    </div>
  </main>;
}

function Home({match,mentality,setMentality,simulate,nextWeek}:any) { return <div><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="label text-[#b7ff39]">SATURDAY · 15 AUGUST 2026</p><h1 className="mt-2 text-4xl font-black md:text-6xl">MATCHDAY</h1><p className="mt-2 text-[#7d8893]">Premier Division · Week 1 · Riverside Stadium</p></div><div className="rounded-xl border border-[#27303c] bg-[#10151c] px-5 py-3"><span className="label">FORM</span><b className="ml-4">W W D W W</b></div></div>
<div className="mt-7 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><div className="rounded-3xl border border-[#27303c] bg-[#0e1319] p-6 md:p-8"><div className="flex items-center justify-between"><p className="label">PREMIER DIVISION</p><span className="rounded-full bg-[#18200f] px-3 py-1 text-[10px] font-black text-[#b7ff39]">HOME</span></div><div className="my-10 grid grid-cols-[1fr_auto_1fr] items-center gap-5 text-center"><div><Badge text="RF"/><h2 className="mt-3 text-xl font-black">Riverside FC</h2><p className="text-xs text-[#737e89]">84 OVR</p></div><div><p className="label">KICK-OFF</p><p className="mt-2 text-4xl font-black">19:45</p><p className="text-xs text-[#737e89]">15 AUG</p></div><div><Badge text="NU"/><h2 className="mt-3 text-xl font-black">Northbridge</h2><p className="text-xs text-[#737e89]">80 OVR</p></div></div>{match ? <div className="rounded-2xl bg-[#151b22] p-5"><p className="label text-center">FULL TIME</p><div className="mt-2 text-center text-5xl font-black"><span>{match.gf}</span><span className="mx-4 text-[#59636e]">—</span><span>{match.ga}</span></div><div className="mt-5 space-y-2">{match.events.map((e:string)=><p key={e} className="border-b border-[#27303c] pb-2 text-sm font-bold last:border-0">{e}</p>)}</div></div>:<div className="grid gap-3 sm:grid-cols-3"><Stat label="TACTIC" value={mentality}/><Stat label="CHEMISTRY" value="91%"/><Stat label="FITNESS" value="94%"/></div>}<div className="mt-6 flex flex-col gap-3 sm:flex-row"><button onClick={simulate} className="flex-1 rounded-xl bg-[#b7ff39] py-4 font-black text-black">SIMULATE MATCH</button><button onClick={nextWeek} className="rounded-xl border border-[#303944] px-6 py-4 text-xs font-black">SKIP WEEK</button></div></div><div className="space-y-5"><div className="rounded-3xl border border-[#27303c] bg-[#0e1319] p-6"><p className="label">MATCH PLAN</p><h3 className="mt-2 text-xl font-black">Choose mentality</h3><div className="mt-5 space-y-2">{["Defensive","Balanced","Attacking"].map(x=><button key={x} onClick={()=>setMentality(x)} className={`w-full rounded-xl border p-4 text-left text-sm font-black ${mentality===x?"border-[#b7ff39] bg-[#18210f] text-[#b7ff39]":"border-[#27303c] bg-[#151b22] text-[#87929e]"}`}>{x}<span className="float-right">{x==="Attacking"?"↑ +4 ATT":""}{x==="Defensive"?"↓ RISK":""}{x==="Balanced"?"● STABLE":""}</span></button>)}</div></div><div className="rounded-3xl border border-[#27303c] bg-[#0e1319] p-6"><p className="label">BOARD OBJECTIVE</p><p className="mt-3 text-2xl font-black">Finish in Top 4</p><div className="mt-5 h-2 rounded-full bg-[#242c34]"><div className="h-full w-[42%] rounded-full bg-[#b7ff39]"/></div><div className="mt-2 flex justify-between text-xs text-[#707b87]"><span>Current: 4th</span><span>42%</span></div></div></div></div></div> }
function Badge({text}:{text:string}){return <div className="mx-auto grid h-20 w-20 place-items-center rounded-2xl border border-[#344027] bg-[#151d0e] text-2xl font-black text-[#b7ff39]">{text}</div>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#151b22] p-4 text-center"><p className="label">{label}</p><p className="mt-2 font-black text-[#b7ff39]">{value}</p></div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <div><p className="label text-[#b7ff39]">CAREER MODE</p><h1 className="mt-2 text-4xl font-black">{title}</h1>{children}</div>}
function Squad(){return <Section title="FIRST TEAM"><div className="mt-7 grid gap-3 md:grid-cols-2">{players.map((p,i)=><div key={p.id} className="rounded-2xl border border-[#27303c] bg-[#0e1319] p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-4"><Badge text={p.pos}/><div><p className="font-black">{p.name}</p><p className="text-xs text-[#707b87]">{p.age} years · {p.pos}</p></div></div><div className="text-right"><p className="text-3xl font-black text-[#b7ff39]">{p.ovr}</p><p className="label">OVR</p></div></div><div className="mt-5 grid grid-cols-4 gap-2">{[["PAC",p.pace],["SHO",p.shoot],["PAS",p.pass],["DEF",p.defend]].map(s=><div key={s[0]} className="rounded-lg bg-[#151b22] p-2 text-center"><p className="text-[9px] text-[#697480]">{s[0]}</p><b className="text-sm">{s[1]}</b></div>)}</div></div>)}</div></Section>}
function Tactics({mentality,setMentality}:any){return <Section title="TACTICAL BOARD"><div className="mt-7 grid gap-5 lg:grid-cols-[1fr_360px]"><div className="rounded-3xl border border-[#27303c] bg-[#10181a] p-6"><div className="mx-auto max-w-xl rounded-[30px] border-2 border-[#42602d] bg-[#102018] p-6"><div className="grid h-[520px] grid-rows-3 gap-3 rounded-2xl border border-[#50723b]/50 bg-[#142a1b] p-6"><div className="grid place-items-center"><div className="player">ST</div></div><div className="flex items-center justify-around"><div className="player">LW</div><div className="player">CAM</div><div className="player">RW</div></div><div className="flex items-center justify-around"><div className="player">CM</div><div className="player">CM</div><div className="player">CDM</div></div></div></div></div><div className="rounded-3xl border border-[#27303c] bg-[#0e1319] p-6"><p className="label">FORMATION</p><p className="mt-2 text-3xl font-black">4-3-3</p><p className="mt-7 label">MENTALITY</p><div className="mt-3 space-y-2">{["Defensive","Balanced","Attacking"].map(x=><button key={x} onClick={()=>setMentality(x)} className={`w-full rounded-xl border p-3 text-sm font-bold ${mentality===x?"border-[#b7ff39] text-[#b7ff39]":"border-[#27303c] text-[#7d8893]"}`}>{x}</button>)}</div><div className="mt-7 rounded-xl bg-[#151b22] p-4"><p className="label">TEAM CHEMISTRY</p><p className="mt-2 text-3xl font-black text-[#b7ff39]">91%</p></div></div></div></Section>}
function Transfers(){return <Section title="TRANSFER MARKET"><div className="mt-7 grid gap-4 md:grid-cols-2">{[['Marco Rossi','ST',24,84,'€42M'],['Leo Martins','CM',20,79,'€25M'],['Samuel Adeyemi','CB',22,81,'€31M'],['Jon Bell','GK',19,74,'€12M']].map(x=><div key={x[0]} className="rounded-2xl border border-[#27303c] bg-[#0e1319] p-5"><div className="flex justify-between"><div><p className="text-lg font-black">{x[0]}</p><p className="text-xs text-[#707b87]">{x[1]} · {x[2]} yrs · Potential 88+</p></div><b className="text-2xl text-[#b7ff39]">{x[3]}</b></div><div className="mt-5 flex items-center justify-between border-t border-[#27303c] pt-4"><span className="text-sm font-bold">Market value {x[4]}</span><button className="rounded-lg bg-[#b7ff39] px-4 py-2 text-xs font-black text-black">SCOUT</button></div></div>)}</div></Section>}
function Fixtures(){return <Section title="FIXTURES"><div className="mt-7 rounded-3xl border border-[#27303c] bg-[#0e1319] p-6">{opponents.map((o,i)=><div key={o} className="flex items-center justify-between border-b border-[#27303c] py-5 last:border-0"><div><p className="label">{15+i*7} AUG 2026</p><p className="mt-1 font-black">{o}</p></div><div className="text-right"><p className="text-xs font-black text-[#b7ff39]">{i%2?'AWAY':'HOME'}</p><p className="text-sm font-bold">{i%2?'20:00':'19:45'}</p></div></div>)}</div></Section>}
function Table(){const teams=['Riverside FC','Kingsport City','Northbridge United','Capital FC','Westford Athletic','Harbor Town','Oakvale United','Redbridge FC'];return <Section title="LEAGUE TABLE"><div className="mt-7 overflow-hidden rounded-3xl border border-[#27303c] bg-[#0e1319]"><div className="grid grid-cols-[40px_1fr_repeat(4,70px)] gap-2 border-b border-[#27303c] p-4 text-[10px] font-black tracking-widest text-[#65707c]"><span>#</span><span>CLUB</span><span>P</span><span>W</span><span>GD</span><span>PTS</span></div>{teams.map((t,i)=><div key={t} className={`grid grid-cols-[40px_1fr_repeat(4,70px)] gap-2 p-4 text-sm ${t==='Riverside FC'?'bg-[#18210f] text-[#b7ff39]':''}`}><b>{i+1}</b><b>{t}</b><span>1</span><span>{i<4?1:0}</span><span>{i<4?2-i:0}</span><b>{i<4?3:1}</b></div>)}</div></Section>}
function Training(){return <Section title="TRAINING"><div className="mt-7 grid gap-4 md:grid-cols-3">{[['ATTACK','Finishing Circuit','+2 SHO'],['MIDFIELD','Passing Patterns','+2 PAS'],['FITNESS','Recovery Run','+3 FIT']].map(x=><button key={x[0]} className="rounded-2xl border border-[#27303c] bg-[#0e1319] p-6 text-left hover:border-[#b7ff39]"><p className="label text-[#b7ff39]">{x[0]}</p><p className="mt-3 text-xl font-black">{x[1]}</p><p className="mt-5 text-xs font-bold text-[#7a8590]">Expected result</p><p className="mt-1 font-black">{x[2]}</p></button>)}</div></Section>}
function Youth(){return <Section title="YOUTH ACADEMY"><div className="mt-7 grid gap-4 md:grid-cols-3">{[['Arjun Patel','CAM',16,68,89],['Tomás Silva','RW',17,71,91],['Eli Brooks','CB',16,64,86]].map(x=><div key={x[0]} className="rounded-2xl border border-[#27303c] bg-[#0e1319] p-5"><Badge text={x[1] as string}/><p className="mt-5 text-lg font-black">{x[0]}</p><p className="text-xs text-[#707b87]">Age {x[2]} · Youth Prospect</p><div className="mt-5 flex justify-between"><span><small className="label">CURRENT</small><b className="ml-2 text-xl">{x[3]}</b></span><span><small className="label">POTENTIAL</small><b className="ml-2 text-xl text-[#b7ff39]">{x[4]}</b></span></div></div>)}</div></Section>}
